[package]
name = "kinexon-nrf"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
nrf52840-hal = "0.16.0"
rtt-target = { version = "0.4.0" }

